services:
  # LangGraph RAG application
  rag:
    image: askme-rag:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: askme-rag
    ports:
      - "8123:8123"
    volumes:
      - ./log:/app/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../config.env
    networks:
      - askme-network

networks:
  askme-network:
    external: true