# Environment Variable Names
# Tavily Configuration
TAVILY_API_KEY="TAVILY_API_KEY"
# LLM Provider Configuration
LLM_PROVIDER="LLM_PROVIDER"  # "ollama", "ollama-cloud", or "gemini"
# Ollama Configuration (local)
OLLAMA_MODEL="OLLAMA_MODEL"
OLLAMA_BASE_URL="OLLAMA_BASE_URL"
OLLAMA_CLOUD_API_KEY="OLLAMA_CLOUD_API_KEY"
# Gemini Configuration
GEMINI_API_KEY="GEMINI_API_KEY"
GEMINI_MODEL="GEMINI_MODEL"
# Common Configuration
MAX_OUTPUT_TOKENS="MAX_OUTPUT_TOKENS"
APP_LOG="APP_LOG"
# LangSmith Configuration
LANGSMITH_TRACING="LANGSMITH_TRACING"
LANGSMITH_ENDPOINT="LANGSMITH_ENDPOINT"
LANGSMITH_API_KEY="LANGSMITH_API_KEY"
LANGSMITH_PROJECT="LANGSMITH_PROJECT"
# Weaviate Configuration
WEAVIATE_COLLECTION_NAME="WEAVIATE_COLLECTION_NAME"
WEAVIATE_SERVER_HOST="WEAVIATE_SERVER_HOST"
WEAVIATE_SERVER_PORT="WEAVIATE_SERVER_PORT"
WEAVIATE_N_RESULTS="WEAVIATE_N_RESULTS"
WEAVIATE_SEARCH_MODE="WEAVIATE_SEARCH_MODE"  # "semantic" or "hybrid"
WEAVIATE_HYBRID_ALPHA="WEAVIATE_HYBRID_ALPHA"  # 0.0..1.0