# Environment Variable Names
# Tavily Configuration
TAVILY_API_KEY="TAVILY_API_KEY"
# LLM Provider Configuration
LLM_PROVIDER="LLM_PROVIDER"  # "ollama", "ollama-cloud", or "gemini"
# Ollama Configuration (local)
OLLAMA_MODEL="OLLAMA_MODEL"
OLLAMA_BASE_URL="OLLAMA_BASE_URL"
# Gemini Configuration
GEMINI_API_KEY="GEMINI_API_KEY"
GEMINI_MODEL="GEMINI_MODEL"
# Common Configuration
MAX_OUTPUT_TOKENS="MAX_OUTPUT_TOKENS"
APP_LOG="APP_LOG"
# LangSmith Configuration
LANGSMITH_TRACING="LANGSMITH_TRACING"
LANGSMITH_ENDPOINT="LANGSMITH_ENDPOINT"
LANGSMITH_API_KEY="LANGSMITH_API_KEY"
LANGSMITH_PROJECT="LANGSMITH_PROJECT"
# ChromaDB Configuration
CHROMA_COLLECTION_NAME="CHROMA_COLLECTION_NAME"
CHROMA_SERVER_HOST="CHROMA_SERVER_HOST"
CHROMA_SERVER_PORT="CHROMA_SERVER_PORT"
CHROMA_N_RESULTS="CHROMA_N_RESULTS"